### ISSUE TITLE
Inconsistent websockets on hosted instance

### ISSUE THREAD

**Issue by luke-riu** [FlowCI/flow-web-x#137]
A lot of the time I will be stuck on this page. Sometimes it works but most of the time I will see this page. It works perfectly when running without the `-h` param when starting the server, but when I run on the hosted instance behind the url, it rarely connects. I have checked my ports are open and routing correctly.
I don't know how to debug this more beyond the browser console logs.

To confirm, I have port forwarded 2015 -> 2015 and 8080 -> 8080

I have tried Chrome, and Safari - both same results. If anyone can think of any ideas to make this work all the time, it would be great. Thanks.

<img width="1267" alt="Screenshot 2021-05-27 at 2 13 58 am" src="https://user-images.githubusercontent.com/75321669/119750603-9be5dc00-be91-11eb-9033-c15a6dc9f8f5.png">

**Comment by gy2006** [comment]
Hi, it seems the server is not started, or something wrong in server-side

  - check if you can access this URL `http://www.your_domin.com:8080/health` (replace domain name)
  
  - check the server log `docker logs -f $(docker ps -aqf "ancestor=flowci/core")`
