### ISSUE TITLE
日志界面不展示日志

### ISSUE THREAD

**Issue by purocean** [FlowCI/flow-web-x#138]
当从页面其他地方点击到 job 详情时候，不能加载出日志，看请求也没有发出。
在此界面重新刷新，就可以正常加载日志

**Comment by gy2006** [comment]
是用的 Chrome 浏览器嘛？

**Comment by purocean** [comment]
> 是用的 Chrome 浏览器嘛？

是的，Chrome 浏览器

**Comment by gy2006** [comment]
感谢，已经修复了，可以拉一下最新的 image `docker pull flowci/web`
