### ISSUE TITLE
官方文档与实际运行不一样

### ISSUE THREAD

**Issue by shaode** [FlowCI/flow-web-x#70]
我用docker上运行，但是flow-web访问和官网文档说的不一样，是版本不一样吗？ 原来线上的版本在哪能看到？

**Comment by yunheli** [comment]
@shaode 请查看这个文档 https://github.com/FlowCI/docs

**Comment by shaode** [comment]
@yunheli 我希望的是能用上官方文档的那些功能，不是现有的这些可以运行之前的程序吗？

**Comment by yunheli** [comment]
@shaode 非常抱歉，线上的服务已经停服务，我们把flowci重新设计了重新开源了，之前在线上能运行的项目在新的flowci上面运行可能要改点东西，非常抱歉

**Comment by shaode** [comment]
@yunheli 太客气了，这个真的是个非常好的项目，不知道以前的是内部使用了还是进行二次改造了，不知道能在哪看到开源的未来整体设计，我先膜拜下；先看下中心思想，现在看源码希望以后能有所贡献，这么好的项目真的不该就这么被砍掉了
